version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: tsj_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tsj_foodies
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: foodies_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/tsj_foodies
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: foodies_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: