 version: "3.9"

 services:

  postgres:
    image: postgres:17
    container_name: tsj_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    container_name: foodies_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      FRONTEND_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: foodies_frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      BACKEND_URL: http://backend:5000
    depends_on:
      - backend

 volumes:
  postgres_data:
